import { describe, expect, test } from "bun:test";
import { telegramUiScenarios } from "./telegram-ui-scenario";

describe("Telegram UI scenario golden", () => {
  test("renders the mobile control surfaces deterministically", () => {
    expect(telegramUiScenarios()).toEqual([
      {
        name: "home",
        text: [
          "🟢 Ready",
          "",
          "Release planning",
          "",
          "GPT-5 · High reasoning",
          "Permissions: Balanced",
        ].join("\n"),
        buttons: [
          ["✨ New chat", "🤖 Model"],
          ["🛡 Permissions", "🧠 Reasoning"],
          ["📋 Tasks", "🗓 Schedules"],
          ["⚡ Fast: Off", "⚙️ More"],
        ],
      },
      {
        name: "home-busy",
        text: [
          "🟡 Working · 35s",
          "",
          "Prepare the release",
          "",
          "Running focused tests",
        ].join("\n"),
        buttons: [
          ["📋 Open task"],
          ["🛑 Stop"],
        ],
      },
      {
        name: "more",
        text: [
          "⚙️ More",
          "",
          "Release planning",
          "",
          "Context",
          "25% context (32,000 / 128,000 tokens)",
          "",
          "Auto-compact",
          "Enabled",
          "",
          "Queue",
          "0 queued",
          "",
          "Session ID",
          "session-42",
        ].join("\n"),
        buttons: [
          ["🗜 Auto-compact: On"],
          ["← Home"],
        ],
      },
      {
        name: "reasoning",
        text: [
          "Choose reasoning depth",
          "",
          "Higher levels spend more time on difficult decisions and code.",
          "",
          "Current",
          "High",
        ].join("\n"),
        buttons: [["Low", "Medium"], ["✓ High", "Extra high"], ["Back to Home"]],
      },
      {
        name: "model-providers",
        text: ["🤖 Model", "", "Current: OpenAI · GPT 5", "", "Choose a provider."].join("\n"),
        buttons: [["Anthropic · 1", "✓ OpenAI · 2"], ["Cancel"]],
      },
      {
        name: "model-page-1",
        text: [
          "🤖 OpenAI models 1/2",
          "",
          "Current: GPT 5 1",
          "",
          "GPT 5 1",
          "✅ gpt-5-1",
          "",
          "GPT 5 10",
          "gpt-5-10",
          "",
          "GPT 5 2",
          "gpt-5-2",
          "",
          "GPT 5 3",
          "gpt-5-3",
          "",
          "GPT 5 4",
          "gpt-5-4",
          "",
          "GPT 5 5",
          "gpt-5-5",
          "",
          "GPT 5 6",
          "gpt-5-6",
          "",
          "GPT 5 7",
          "gpt-5-7",
        ].join("\n"),
        buttons: [
          ["✓ GPT 5 1", "GPT 5 10"],
          ["GPT 5 2", "GPT 5 3"],
          ["GPT 5 4", "GPT 5 5"],
          ["GPT 5 6", "GPT 5 7"],
          ["← Back", "Next →"],
          ["Cancel"],
        ],
      },
      {
        name: "model-page-2-selected",
        text: [
          "🤖 OpenAI models 2/2",
          "",
          "Current: GPT 5 9",
          "",
          "GPT 5 8",
          "gpt-5-8",
          "",
          "GPT 5 9",
          "✅ gpt-5-9",
        ].join("\n"),
        buttons: [["GPT 5 8", "✓ GPT 5 9"], ["← Back", "← Prev"], ["Cancel"]],
      },
      {
        name: "schedules-list",
        text: [
          "🗓 Schedules",
          "",
          "2 schedules",
          "",
          "🟢 Morning brief",
          "Next: Today at 3:13 PM Pacific",
          "",
          "⏸ Exotic sync",
          "⚠️ Next: Paused",
          "Last error: Gateway unavailable",
        ].join("\n"),
        buttons: [
          ["Morning brief", "Exotic sync"],
          ["Create schedule"],
          ["← Home"],
        ],
      },
      {
        name: "schedule-detail",
        text: [
          "🟢 Morning brief",
          "",
          "Summarize overnight changes",
          "",
          "Schedule",
          "Every day at 9:00 AM (Pacific)",
          "",
          "Next run",
          "Today at 3:13 PM Pacific",
          "",
          "Status",
          "Active · 4 succeeded, 0 failed",
        ].join("\n"),
        buttons: [
          ["Run now", "Pause"],
          ["Edit"],
          ["⚠️ Delete"],
          ["← Back"],
        ],
      },
      {
        name: "schedule-detail-exotic",
        text: [
          "⏸ Exotic sync",
          "",
          "Sync mid-month stats",
          "",
          "Schedule",
          "23 4 1,15 * 2 (Pacific)",
          "",
          "Next run",
          "Paused",
          "",
          "Status",
          "Paused · 1 succeeded, 1 failed",
          "",
          "Last error",
          "⚠️ Gateway unavailable",
        ].join("\n"),
        buttons: [
          ["Run now", "Resume"],
          ["Edit"],
          ["⚠️ Delete"],
          ["← Back"],
        ],
      },
      {
        name: "schedule-delete-confirm",
        text: [
          "Delete schedule?",
          "",
          "Delete \"Morning brief\" permanently?",
          "",
          "⚠️ This schedule will be permanently deleted.",
        ].join("\n"),
        buttons: [
          ["⚠️ Delete schedule"],
          ["Cancel"],
        ],
      },
      {
        name: "schedule-delete-settled",
        text: [
          "Delete schedule?",
          "",
          "\"Morning brief\" has been deleted.",
          "",
          "✅ ✅ Deleted",
        ].join("\n"),
        buttons: [
          ["🗓 Schedules"],
          ["Back to Home"],
        ],
      },
      {
        name: "active-task",
        text: [
          "🟡 Working · 30s",
          "",
          "Prepare the release",
          "",
          "Release",
          "✓ Confirm package contents",
          "● Run release checks",
          "○ Publish package",
          "",
          "Recent activity",
          "✓ Checking release gates",
          "→ Running focused tests",
        ].join("\n"),
        buttons: [
          ["✏️ Add instruction", "➕ Add follow-up"],
          ["🛑 Stop"],
        ],
      },
      {
        name: "failed-task",
        text: [
          "⚠️ Failed · 30s",
          "",
          "Deploy the release",
          "",
          "Recent activity",
          "→ Deploying the selected build",
          "",
          "What happened",
          "⚠️ The task took longer than expected.",
        ].join("\n"),
        buttons: [
          ["↻ Retry", "🔍 View details"],
          ["📋 Open task", "✨ Start fresh"],
        ],
      },
      {
        name: "failed-task-details",
        text: [
          "⚠️ Failed · 30s",
          "",
          "Deploy the release",
          "",
          "Recent activity",
          "→ Deploying the selected build",
          "",
          "What happened",
          "⚠️ The task took longer than expected.",
          "",
          "Details",
          "Provider socket timed out",
        ].join("\n"),
        buttons: [
          ["↻ Retry", "Hide details"],
          ["📋 Open task", "✨ Start fresh"],
        ],
      },
      {
        name: "decision-approved",
        text: ["Approve deployment", "", "Deploy the selected build?", "", "✅ Approved once"].join("\n"),
        buttons: [],
      },
      {
        name: "decision-denied",
        text: ["Approve deployment", "", "Deploy the selected build?", "", "🚫 Denied"].join("\n"),
        buttons: [],
      },
      {
        name: "decision-expired",
        text: ["Approve deployment", "", "Deploy the selected build?", "", "⌛ Expired — the agent is still waiting"].join(
          "\n",
        ),
        buttons: [],
      },
    ]);
  });
});
