import { describe, expect, test } from "bun:test";
import { telegramUiScenarios } from "./telegram-ui-scenario";

describe("Telegram UI scenario golden", () => {
  test("renders the mobile control surfaces deterministically", () => {
    expect(telegramUiScenarios()).toEqual([
      {
        name: "home",
        text: [
          "🟢 OmpClaw · Idle",
          "",
          "Release planning",
          "",
          "Session",
          "25% context",
          "",
          "Model",
          "openai/gpt-5",
          "",
          "Mode",
          "Balanced · high",
          "",
          "Controls",
          "Fast off · Auto-compact on",
        ].join("\n"),
        buttons: [
          ["📊 Status", "🤖 Model"],
          ["🛡 Autonomy", "🧠 Reasoning"],
          ["⚡ Fast mode", "🗜 Auto-compact"],
          ["📋 Tasks", "🗓 Jobs"],
          ["✨ New session"],
        ],
      },
      {
        name: "reasoning",
        text: [
          "Choose reasoning depth",
          "",
          "Higher levels spend more time on difficult decisions and code.",
          "",
          "Current",
          "High",
        ].join("\n"),
        buttons: [["Low", "Medium"], ["✓ High", "Extra high"], ["Back to Home"]],
      },
      {
        name: "model-providers",
        text: ["🤖 Model", "", "Current: OpenAI · GPT 5", "", "Choose a provider."].join("\n"),
        buttons: [["Anthropic · 1", "✓ OpenAI · 2"], ["Cancel"]],
      },
      {
        name: "model-page-1",
        text: [
          "🤖 OpenAI models 1/2",
          "",
          "Current: GPT 5 1",
          "",
          "GPT 5 1",
          "✅ gpt-5-1",
          "",
          "GPT 5 10",
          "gpt-5-10",
          "",
          "GPT 5 2",
          "gpt-5-2",
          "",
          "GPT 5 3",
          "gpt-5-3",
          "",
          "GPT 5 4",
          "gpt-5-4",
          "",
          "GPT 5 5",
          "gpt-5-5",
          "",
          "GPT 5 6",
          "gpt-5-6",
          "",
          "GPT 5 7",
          "gpt-5-7",
        ].join("\n"),
        buttons: [
          ["✓ GPT 5 1", "GPT 5 10"],
          ["GPT 5 2", "GPT 5 3"],
          ["GPT 5 4", "GPT 5 5"],
          ["GPT 5 6", "GPT 5 7"],
          ["← Back", "Next →"],
          ["Cancel"],
        ],
      },
      {
        name: "model-page-2-selected",
        text: [
          "🤖 OpenAI models 2/2",
          "",
          "Current: GPT 5 9",
          "",
          "GPT 5 8",
          "gpt-5-8",
          "",
          "GPT 5 9",
          "✅ gpt-5-9",
        ].join("\n"),
        buttons: [["GPT 5 8", "✓ GPT 5 9"], ["← Back", "← Prev"], ["Cancel"]],
      },
      {
        name: "jobs",
        text: [
          "Scheduled jobs",
          "",
          "1 job",
          "",
          "Morning brief",
          "Active",
          "Cron · 0 9 * * * · America/Los_Angeles",
          "Next · 2023-11-14T23:13:20.000Z",
        ].join("\n"),
        buttons: [
          ["Pause · Morning brief", "Run now · Morning brief"],
          ["⚠️ Delete · Morning brief"],
          ["Back to Home"],
        ],
      },
      {
        name: "active-task",
        text: [
          "🟡 Working · 30s",
          "",
          "Prepare the release",
          "",
          "Release",
          "✓ Confirm package contents",
          "● Run release checks",
          "○ Publish package",
          "",
          "Recent activity",
          "✓ Checking release gates",
          "→ Running focused tests",
        ].join("\n"),
        buttons: [["✏️ Add instruction", "➕ Add follow-up"], ["🛑 Stop"]],
      },
      {
        name: "decision-approved",
        text: ["Approve deployment", "", "Deploy the selected build?", "", "✅ Approved once"].join("\n"),
        buttons: [],
      },
      {
        name: "decision-denied",
        text: ["Approve deployment", "", "Deploy the selected build?", "", "🚫 Denied"].join("\n"),
        buttons: [],
      },
      {
        name: "decision-expired",
        text: [
          "Approve deployment",
          "",
          "Deploy the selected build?",
          "",
          "⌛ Expired — the agent is still waiting",
        ].join("\n"),
        buttons: [],
      },
    ]);
  });
});
